sudo: required
services:
  - docker
language: node_js
node_js:
  - "8"
script:
  - yarn install
  - yarn run build
  - yarn run test
  - yarn run coveralls
cache:
  directories:
    - "node_modules"
  yarn: true
after_success:
  - (test "$TRAVIS_TAG" != "" || test "$TRAVIS_BRANCH" = "dev") && docker build -t gyselroth/kube-ldap:$TRAVIS_BRANCH .
  - (test "$TRAVIS_TAG" != "" || (test "$TRAVIS_BRANCH" = "dev" && test "$TRAVIS_PULL_REQUEST" = "false")) && docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - test "$TRAVIS_TAG" != "" && docker tag gyselroth/kube-ldap:$TRAVIS_BRANCH gyselroth/kube-ldap:latest
  - (test "$TRAVIS_TAG" != "" || (test "$TRAVIS_BRANCH" = "dev" && test "$TRAVIS_PULL_REQUEST" = "false")) && docker push gyselroth/kube-ldap:$TRAVIS_BRANCH
  - test "$TRAVIS_TAG" != "" && docker push gyselroth/kube-ldap:latest
